SailingSite/Controllers/AnimalController.cs
namespace SailingSite.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web;
    using System.IO;
    using System.Net;
    using System.Web.Mvc;

    using SailingSite.Common;
    using SailingSite.ViewModels;

    using SailingSiteModels.New;

    public class AnimalController : BaseController
    {
        public AnimalController()
        {
            
        }

        public ActionResult Test()
        {
            return View();
        }
        //
        // GET: /Animal/
        public ActionResult Index()
        {
            var model=this.AnimalService.GetTopLevelCategories();
            return View(model);
        }

        public ActionResult GetAllCategories()
        {
            var model=this.AnimalService.GetAllCategories();
            return View(model);
        }

        public ActionResult DeleteCategory(string name)
        {
            string parent = null;
            string error=null;
            try
            {
                parent = this.AnimalService.DeleteCategory(name);
            }
            catch (Exception e)
            {
                error = e.Message;
            }
            base.FlagCacheUpdate(StaticTokens.CachingTokens.AnimalEnum);
            var model=this.AnimalService.GetCategory(parent);
            return PartialView("CategoryList", model);
        }

        public ActionResult DeleteAnimal(int id)
        {
            if (CurrentUser != null && CurrentUser.SID >= Crew.SIDEnum.PowerUser)
            {
                LocationService.DeleteLandMark(id, CurrentUser.ID);
                return new HttpStatusCodeResult(HttpStatusCode.Accepted);
            }
            string error = null;
            string parent = null;
            try
            {
                parent = this.AnimalService.DeleteAnimal(id);
            }
            catch (Exception e)
            {
                error = e.Message;
            }
            base.FlagCacheUpdate(StaticTokens.CachingTokens.AnimalEnum);
            return RedirectToAction("GetCategory", new { name = parent});
        }

        public ActionResult SearchByLetter(string letter)
        {
            var request = new GeneralSearchRequest();
            if (string.IsNullOrEmpty(letter) || !char.IsLetter(letter[0]))
            {
                this.AnimalService.Search(request);
            }
            request.FirstInitial = letter;
            var data = this.AnimalService.Search(request);
            return this.View("_ZooSearch", data);

        }

        public ActionResult GetCategory(string name)
        {
            if (name == null)
            {
               var first=this.AnimalService.GetAllCategories();
               if (first != null&&first.Any())
               {
                   name = first.First().Name;
               }
            }
            var categories = this.AnimalService.GetSiblingCategories(name);
            if (categories != null)
            {
                TempData["SisterCategories"] = categories;
            }
            var model = this.AnimalService.GetCategory(name);
            return View(model);
        }

        public ActionResult GetAnimal(int id=1)
        {
           
            if (Session["Tags"] == null)
            {
                var strings=this.TagService.GetAllTagsByString();
                Session["Tags"] = strings;
            }
            Session["Crew"] = true;
            var Animal = this.AnimalService.GetDetailedAnimal(id);
            //TODO: Merge animal and GetAnimal
            return View(Animal);
        
        }

        public ActionResult DeleteTag(int id, int entityId)
        {
            this.AnimalService.DeleteAnimalTag(id, entityId);
            var result = this.AnimalService.GetAnimalTags(entityId);
            return PartialView("TagList", result);
        }

        public void CreateCategory(string name, string category)
        {
            if (string.IsNullOrEmpty(category)||category.ToLower()=="null")
            {
                category = null;
            }
            var entity = new SailingSiteModels.New.AnimalCategory();
            entity.Name = name;
            entity.ParentName = category;

            this.AnimalService.CreateCategory(entity);
            RedirectToAction("GetCategory", new { name = category });
        }

        public ActionResult Create(Animal entity, string tagList, HttpPostedFileBase file)
        {
            if (this.CurrentUser == null || (this.CurrentUser != null && this.CurrentUser.SID < Crew.SIDEnum.PowerUser))
            {
                var model = new RedirectModel() { Description = "You must be an admin to complete this task." };

                return this.View("NoPermissionPage", model);
            }
            Photo photo=null;
            if (file != null)
                {
                    photo = new SailingSiteModels.New.Photo() { Name = entity.Name, FileName = file.FileName, EntityName = entity.Name, Subdirectory = @Resources.SessionVariables.ImageFolderCrew };
                    photo.ID = this.PhotoService.SavePhoto(file, photo, this.Context, Server.MapPath("~/imagedir"));
                    entity.Photo = photo;
                }

            if (entity.ID > 0)
            {
                AnimalService.UpdateAnimal(entity, this.Context);
            }
            else
            {
                AnimalService.CreateAnimal(entity, this.Context);
            } 

            base.FlagCacheUpdate(StaticTokens.CachingTokens.AnimalEnum);
            return RedirectToAction("GetCategory", new { name = entity.Category });
        }

        public ActionResult UpdateCategory(string name)
        {
            var Names = this.AnimalService.GetAllCategories();
            var category = this.AnimalService.GetCategory(name);
            TempData["AnimalCategories"] = Names.ToList();
            return View(category);
        }

        public ActionResult Patch(SailingSiteModels.New.Animal entity, string aliases, HttpPostedFileBase file)
        {
            string error=null;
            var animal = new SailingSiteModels.New.Animal(entity, aliases);
            if (file != null)
            {
                var photo = new SailingSiteModels.New.Photo() { Name = animal.Name, FileName = file.FileName, EntityName = animal.Name, Subdirectory = Resources.SessionVariables.ImageFolderAnimal };
                photo.ID = this.PhotoService.SavePhoto(file, photo, this.Context, Server.MapPath("~/imagedir"));
                animal.Photo = photo;
            }
            try
            {
                this.AnimalService.UpdateAnimal(animal, this.Context);
            }
            catch (Exception e)
            {
                error = e.Message;
            }
            return RedirectToAction("Update", new { id=entity.ID.ToString(), error=error });
        }

        public ActionResult AddComment(int entityId, SailingSiteModels.New.Comment comment)
        {
            if (comment.ID > 0)
            {
                this.CommentService.Update(comment);
            }
            else
            {
                comment.ID = this.CommentService.Create(comment);
            }
            this.AnimalService.AddAnimalComment(comment, entityId);
            var data = AnimalService.GetAnimalComments(entityId);
            ViewData["controller"] = "animal";
            ViewData["entityID"] = entityId;
            return PartialView(data);
        }

        public ActionResult AddTags(int id, string tags)
        {
            this.AnimalService.AddTags(id,tags);
            var result = this.AnimalService.GetAnimalTags(id).ToArray();
            ViewData["controller"] = "animal";
            ViewData["entityID"] = id;
            return PartialView("TagList", result);
        }

        public ActionResult PatchCategory(SailingSiteModels.New.AnimalCategory entity)
        {

            string parent = null;
            try
            {
                parent = this.AnimalService.UpdateCategory(entity, this.Context);
            }
            catch (Exception e)
            {
                var error = e.Message;
                return RedirectToAction("UpdateCategory", new { name = entity.Name});
            }
            if (parent == null)
            {
                return RedirectToAction("GetAllCategories");
            }
            else return RedirectToAction("GetCategory", new { name = parent });
        }


        public ActionResult New(string category=null, string name=null, string keywords=null, string description=null, string error=null)
        {
            if (this.CurrentUser != null || (this.CurrentUser != null && this.CurrentUser.SID < Crew.SIDEnum.Admin))
            {
                var model = new RedirectModel() { Description = "You must be an admin to complete this task." };

                return this.View("NoPermissionPage", model);
            }

            this.GetSessionVariables();
            return View();

        }

        public ActionResult GetAnimalsForCategory(string category)
        {
            var result = this.AnimalService.GetCategory(category);
            return PartialView("AnimalList");
        }

        public ActionResult NewCategory(string category = null, string name = null, string error = null)
        {
            var Names = this.AnimalService.GetAllCategories();
            Session["AnimalCategories"] = Names.ToList();
            if (!string.IsNullOrEmpty(error))
            {
                TempData["Error"] = error;
            }

            if (!string.IsNullOrEmpty(category))
            {
                TempData["Category"] = category;
            }
            if (!string.IsNullOrEmpty(name))
            {
                TempData["Name"] = name;
            }
            return View();

        }
	}
}

SailingSite/Views/Animal/Animal.cshtml
@using SailingSite.Common
@model SailingSiteModels.New.AnimalCategory
@{
    bool authorized = true;
    
}
<table id="Animals">
    <tr>
        <th>Photo</th>
        <th>Name</th>
        <th>Description</th>
        @if (authorized)
        {
            <th>Edit</th>
        }

    </tr>
    @foreach (var animal in Model.Animals)
    {
        <tr>
            <td class="thumbnail"><img src=@animal.Photo.Path/></td>
            <td class="value">@Html.ActionLink(animal.Name,"GetAnimal",new {id=animal.ID})</td>
            <td class="value"> @animal.Description.Chop(100)    
                              </td>

        </tr>
    }
</table>

<script>
    
</script>

SailingSite/Views/Animal/AnimalList.cshtml
@model SailingSiteModels.New.AnimalCategory
@using SailingSite.Common
@{
    List<SailingSiteModels.New.AnimalCategory> sisterCats = null;
    if (TempData["SisterCategories"] != null)
    {
        sisterCats = ((IEnumerable<SailingSiteModels.New.AnimalCategory>)TempData["SisterCategories"]).ToList();
    }
    }
@{

    
    if (Model.Animals != null && Model.Animals.Any())
    {<h2>@Model.Animals.Count() Animals:</h2><br />
        <table id="Animals">
    <tr>

        <th>Name</th>
        <th>Description</th>
        <th>Edit</th>
        <th>Reassign</th>
        <th>Delete</th>
        
    </tr>
        @foreach (var animal in Model.Animals)
        {

        <tr data-animalid="@animal.ID">
            <td class="thumbnail">
            @if (animal.Photo!=null&&animal.Photo.ThumbPath!=null)
            { 
            <img src="@animal.Photo.ThumbPath"/>
            }
                                                </td>
            <td class="value">@Html.ActionLink(@animal.Name,"GetAnimal",new {id=animal.ID.ToString()},null)</td>
            <td class="value">@if (animal.Description!=null){
                                  @animal.Description.Chop(100)
            }</td>
            <td class="value">@Html.ActionLink("Edit", "Update", new { id = animal.ID.ToString() }, null)</td>
            <td class="value">
                <select id="@animal.ID">
                    @if (sisterCats!=null&&sisterCats.Any())
                    {
                    foreach (var cat in sisterCats)
                    { 
                    <option value="@cat.ID">@cat.Name</option>
                    }
                    }
            </select>

            </td>
            <td><button class="Delete">Delete</button></td>
        </tr>
            
        }
    </table>
    @Html.ActionLink("Transition all animals","GetAnimal",new {id=Model.Name},null)
    }

}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script>
        function deleteitem(e) {
        var tr=$(this).parents("tr");
        var id=tr.attr("data-categoryId");
        $.ajax({
        url: "/Animal/Delete/" ,
        failure:"formError" ,
        data: { "id":id},
        type: "POST" ,
        datatype: "html" ,
        success: function (e) {
        $("#list").html((e));
        },
        complete: function (e) { 
                }
                });
                }

                $(".delete").on("click", deleteItem);
    });
                </script>

SailingSite/Views/Animal/CategoryList.cshtml
@model SailingSiteModels.New.AnimalCategory
@using SailingSite.Common
@{
    List<SailingSiteModels.New.AnimalCategory> sisterCats = null;
    if (TempData["SisterCats"] != null)
    {
        sisterCats = (List<SailingSiteModels.New.AnimalCategory>)TempData["SisterCats"];
    }
}
@{


    if (Model.Subcategories != null && Model.Subcategories.Any())
    {<h2>@Model.Subcategories.Count() Categories:</h2><br />

    <table id="categories" class="tablesorter">
        <thead>
            <tr>
                <th>Photo</th>
                <th>Name</th>
                <th>Description</th>
                <th>Edit</th>
                <th>Delete</th>

            </tr>
        </thead>
        <tbody>
            @foreach (var category in Model.Subcategories.OrderBy(i => i.Name))
            {

                <tr data-animalid="@category.ID">
                    <td class="thumbnail">
                        @if (category.Photo != null)
                        {<img src="@category.Photo.ThumbPath" />}
                </td>
                <td class="value">@Html.ActionLink(category.Name, "GetCategory", new { name = category.Name.ToString() }, null)</td>
                <td class="value">@category.Description.Chop(100)</td>
                <td class="value">@Html.ActionLink("Edit", "UpdateCategory", new { name = category.Name.ToString() }, null)</td>
                <td class="value">
                    @if (sisterCats != null && sisterCats.Any())
                    {
                        <select id="@category.ID">
                            @foreach (var cat in sisterCats)
                            {
                                <option value="@cat.ID">@cat.Name</option>
                            }

                        </select>
                    }

                </td>
                <td><button class="Delete">Delete</button></td>
            </tr>

            }
        </tbody>
    </table>
    }

}
<script>
    function deleteitem(e) {
        var tr=$(this).parents("tr");
        var id=tr.attr("data-categoryId");
        $.ajax({
            url: "/Animal/DeleteCategory/" ,
            failure:"formError" ,
            data: { "id":id},
            type: "POST" ,
            datatype: "html" ,
            success: function (e) {
                $("#subcategory").html((e));
            },
            complete: function (e) {
            }
        });
    }
    $(document).ready(function() 
    { 
        $("#categories").tablesorter(); 
        $(".delete").on("click", deleteItem);
    } 
); 
    

   
   
</script>

SailingSite/Views/Animal/CommentList.cshtml
@model IEnumerable<SailingSiteModels.New.Comment>
@using SailingSite.Common
<table id="CommentTable">
 @foreach (var comment in Model)
 { 
    <tr>
        <td>
            <table>
                <tr>
                    <td class="commentheader">@comment.CreatedBy <label> on </label>@Html.ActionLink(@comment.Created.ToString(),"Get","Comment", new{id=comment.ID})</td>
                </tr>
            </table>

        </td>
        <td>
            @comment.Message.Chop(250)
        </td>
    </tr>
 }

</table>

SailingSite/Views/Animal/GetAllCategories.cshtml
@model IEnumerable<SailingSiteModels.New.AnimalCategory>
@{
    ViewBag.Title = "GetAllCategories";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<h2>GetAllCategories</h2>
<table>
    <tr>
        <td class="label">Category Name</td>
        </tr>
        @{foreach (var i in Model)
          {
              <tr> 
            <td>@Html.ActionLink(i.Name, "GetCategory", "Animal", new { name=i.Name}, null)</td>
                  </tr>  
        }    
          }
    
</table>

SailingSite/Views/Animal/GetAnimal.cshtml
<script type="text/javascript" charset="utf8" src="~/bundles/jquery.dataTables-1.10.7.min.js"></script>
<link href="~/bundles/jquery.dataTables-1.10.7.min.css" rel="stylesheet" />
<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
<link href="~/bundles/jquery-ui.min.css" rel="stylesheet" />

@model SailingSiteModels.New.AnimalDetails
           <title>@Model.Name</title>
@{

    ViewData["controller"] = "animal";
    ViewData["entityID"] = Model.ID;
}
@{
    <table>
        <tr>
            @if (Model.Photo != null && Model.Photo.ThumbPath != null)
{
            <td class="photo">
             
            <img src=@Model.Photo.ThumbPath /></td>
            }
                <td class="title">
            
    <h1>@Model.Name</h1>
</td>
        </tr>
        <tr>
            <td class="classification">@Html.LabelFor(i => i.Category, Model.Category)</td>
        </tr>
    </table>
    <div id="accordion">
        <h3>Description</h3>
        <div>
            <p>@Model.Description</p>
        </div>
        <h3>Aliases</h3>
        <div>
            <p>@Model.GetAliases()</p>

        </div>

        <h3>Comments</h3>
        <div id="commentDiv" class="ui-widget">
        @Html.Partial("_CommentList", Model.Comments);
        </div>
    
        <h3>Tags</h3>
        <div id="tagdiv" class="ui-widget">
            @Html.Partial("TagList", Model.Tags)

        </div>
        
        @if (Model.Photos != null && Model.Photos.Any())
        { 
         <h3>Photos</h3>
        <div>
            @Html.Partial("PhotoTable", Model.Photos);
        </div>
        }
        @if (Model.Spottings!=null&Model.Spottings.Any())
        {
    <h3>Sightings: (@Model.Spottings.Count)</h3>
    <div>
        @Html.Partial("SailBaseTable", Model.Spottings);
    </div>
        }
    </div>
}





}
<script>



    $("#accordion").accordion({
        collapsible: true
    });



    </script>

SailingSite/Views/Animal/GetCategory.cshtml
@model SailingSiteModels.New.AnimalCategory
@{
    IEnumerable<SailingSiteModels.New.AnimalCategory> categories=null;
    if (TempData["Categories"]!=null)
    {
        categories=(IEnumerable<SailingSiteModels.New.AnimalCategory>)TempData["Categories"];
    }
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@Model.Name</title>
</head>
<body>
    <div>
        <div class="title">@Model.Name</div>
        <div id="subcategories">
            @Html.Partial("CategoryList")
        </div>
         <div id="list">
            @Html.Partial("AnimalList")
        </div>
}@Html.ActionLink("Create Animal", "New", "Animal", new { category = Model.ID }, htmlAttributes: null);
@Html.ActionLink("New Category", "NewCategory", "Animal", new { category = Model.ID }, htmlAttributes: null);
    </div>
    
</body>
</html>

SailingSite/Views/Animal/Index.cshtml
@model SailingSiteModels.New.AnimalCategory
@{
    ViewBag.Title = "Animals";
    
}
<head>
    <script type="text/javascript" charset="utf8" src="~/bundles/jquery.dataTables-1.10.7.min.js"></script>
    <link href="~/bundles/jquery.dataTables-1.10.7.min.css" rel="stylesheet" />
        </head>
        <html><h1>@Model.Name</h1>
        <body>
            <div id="subcategories">
                @Html.Partial("CategoryList")
            </div>
        </body>
        </html>

SailingSite/Views/Animal/New.cshtml
@using SailingSite.App_GlobalResources
@model SailingSiteModels.New.Animal
@{
    
    ViewBag.Title = "New";
    var Categories = new List<SailingSiteModels.New.AnimalCategory>();
    var currCategory = "";
    var error = "";
    var name="";
    var keywords = "";
    var description = "";
    var updateDesc = (Model==null||Model.ID > 0) ? "Update" : "Add";
    if (TempData["Description"]!=null)
    {
        description = TempData["Description"].ToString();
    }
    if (TempData["Name"] != null)
    {
        name = TempData["Name"].ToString();
    }
    if (TempData["Keywords"] != null)
    {
        keywords = TempData["Name"].ToString();
    }

    if (Session["AnimalCategories"]!=null)
    {
        var list = Session["AnimalCategories"] as SailingSiteModels.New.AnimalCategory[];
        if (list != null)
        {
            Categories = list.ToList();
        }
    }
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@{if(!string.IsNullOrEmpty(error))
  {
<div id="Error">Error: @error</div>
}
}

@using (Html.BeginForm("create", "animal", FormMethod.Post, new { enctype = "multipart/form-data" })) { 
<table id="newAnimal">
    <tr>
        @Html.HiddenFor(i=>i.ID)
        <td class="Label">Name:</td><td>@Html.TextBoxFor(i=>i.Name)
    </tr>
    <tr>
        <td class="Label">Category</td><td><select id="AnimalCategory" name="Category">
                                               @foreach (var category in Categories)
                                               {
                                                   string selected=String.Empty;
                                                   if (!string.IsNullOrEmpty(currCategory))
                                                   {
                                                       if (category.Name.Equals(Model.Category,StringComparison.CurrentCultureIgnoreCase))
                                                       {
                                                           selected = "selected";
                                                       }
                                                   }
                                                       <option value=@category.Name @selected>@category.Name</option>

                                               }
        </select>
        </td>

    </tr>
    <tr>
        <td class="Label">Description</td>
        <td>
            @Html.TextArea("Description",description,6,6,null)
        </td>

    </tr>
        <tr>
            <td class="label">
                Aliases (Comma delimited list):
            </td>
            <td>@Html.TextAreaFor(i=>i.Aliases)
            </tr>
    <tr>
        <td>@SharedStrings.PhotoLabel</td>
        <td><input type="file" id="file" name="file" accept="image/*"/></td>
    </tr>
    <tr>
        <td>@Html.Partial("TagListv3",Model)</td>
    </tr>
    <tr>
        <td>
            <input type="Submit" value="@updateDesc" />
        </td>

    </tr>
</table>
}

SailingSite/Views/Animal/NewCategory.cshtml
@model SailingSiteModels.New.AnimalCategory
@{

    ViewBag.Title = "New";
    var Categories = new List<SailingSiteModels.New.AnimalCategory>();
    var currCategory = "";
    var error = "";
    var name = "";
    var keywords = "";
    var description = "";
    if (TempData["Name"] != null)
    {
        name = TempData["Name"].ToString();
    }
    if (TempData["Error"] != null)
    {
        error = TempData["Error"].ToString();
    }
    if (TempData["Category"] != null)
    {
        currCategory = TempData["Category"].ToString();
    }
    if (Session["AnimalCategories"] != null)
    {
        Categories = (List<SailingSiteModels.New.AnimalCategory>)Session["AnimalCategories"];
    }
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@{if (!string.IsNullOrEmpty(error))
{
    <div id="Error">Error: @error</div>
}
}

@using (Html.BeginForm("createcategory", "animal", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <table id="newAnimal">
        <tr>
            <td style:"label">Name:</td>
            <td><input id="AnimalName" type=text name="name" />@name</td>
        </tr>
        <tr>
            <td style:"label">Category</td>
            <td>
                <select id="AnimalCategory" name="category">
                    <option value="Null">None (Top Level)</option>
                    @foreach (var category in Categories)
                    {
                        bool selected = false;
                        if (!string.IsNullOrEmpty(currCategory))
                        {
                            if (category.Name.ToLower().Trim() == currCategory.ToLower().Trim())
                            {
                                selected = true;
                            }
                        }
                        if (selected)
                        {
                            <option value=@category.Name selected>@category.Name</option>
                        }
                        else
                        {
                            <option value=@category.Name>@category.Name</option>
                        }
                    }
                </select>
            </td>

        </tr>
        <tr>
        <td>
            <input type="Submit" value="Save" />
        </td>

        </tr>
    </table>
}

SailingSite/Views/Animal/Test.cshtml
<html>
<head>
    
    <script type="text/javascript" charset="utf8" src="~/bundles/jquery.dataTables-1.10.7.min.js"></script>
    <link href="~/bundles/jquery.dataTables-1.10.7.min.css" rel="stylesheet" />
    <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
    <link href="~/bundles/jquery-ui.min.css" rel="stylesheet" />
</head>
<body>
    <div id="accordion">
        <h3>Test1</h3>
        <div>
            Our first test!
        </div>
        <h3>Test2</h3>
        <div>
            Our second test!!

        </div>
    </div>
    <table id="table_id" class="display">
        <thead>
            <tr>
                <th>Last Name</th>
                <th>First Name</th>
                <th>Email</th>
                <th>Due</th>
                <th>Web Site</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>Smith</td>
                <td>John</td>
                <td>jsmith@gmail.com</td>
                <td>$50.00</td>
                <td>http://www.jsmith.com</td>
            </tr>
            <tr>
                <td>Bach</td>
                <td>Frank</td>
                <td>fbach@yahoo.com</td>
                <td>$50.00</td>
                <td>http://www.frank.com</td>
            </tr>
            <tr>
                <td>Doe</td>
                <td>Jason</td>
                <td>jdoe@hotmail.com</td>
                <td>$100.00</td>
                <td>http://www.jdoe.com</td>
            </tr>
            <tr>
                <td>Conway</td>
                <td>Tim</td>
                <td>tconway@earthlink.net</td>
                <td>$50.00</td>
                <td>http://www.timconway.com</td>
            </tr>
        </tbody>
    </table>
    <fieldset class="majorpoints">
        <legend class="majorpointslegends"><label class="icon">[+]</label>Expand</legend>
        <div class="hiders" style="display:none">This is the content that was hidden before, but now is... Well, visible!"</div></fieldset>
    <fieldset class="majorpoints">
        <legend class="majorpointslegends">Expand<label class="icon">[+]</label></legend>
        <div class="hiders" style="display:none">This is the content that was hidden before, but now is... Well, visible!"</div>
    </fieldset>
    <fieldset class="majorpoints">
        <legend class="majorpointslegends">Expand<label class="icon">[+]</label></legend>
        <div class="hiders" style="display:none">This is the content that was hidden before, but now is... Well, visible!"</div>
    </fieldset>
           
</body>
</html>   

<script type="text/javascript">
    $(document).ready(function () {
        $('#table_id').DataTable();
        
        $("#accordion").accordion({
            collapsible: true
        });

        $('.majorpoints').click(function () {
            $(this).find('.hiders').toggle();
            var i = $(this).find('.icon').text();
            if (i.toString().indexOf('+') > 0) {
                $(this).find('.icon').text('[-]');
            }
            else {
                $(this).find('.icon').text('[+]');
            }

        });
        
    });

</script>

SailingSite/Views/Animal/UpdateCategory.cshtml
@model SailingSiteModels.New.AnimalCategory
@{
    ViewBag.Title = "Update";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var animal = Model;
    IEnumerable<SelectListItem> Categories=null; 
    if (TempData["AnimalCategories"] != null)
    {
        Categories = (IEnumerable<SelectListItem>)((List<SailingSiteModels.New.AnimalCategory>)TempData["AnimalCategories"]).Select(i=>new SelectListItem {Value=i.Name, Text=i.Name });
        SelectListItem[] Array=new SelectListItem[] {new SelectListItem{Text="Top Level",Value="Null"}};
        Categories = Categories.Concat(Array);
        if (Model.ParentName == null)
        {
            Model.ParentName = "Null";
        }
    }
    string error = null;
    if (TempData["Error"] != null)
    {
        error = TempData["Error"].ToString();
    }


}
<h2>UpdateCategory</h2>
@{ if (error!=null)
   { 
    <div class="Error">
        ***@error***
    </div>
}
}

@using (Html.BeginForm("PatchCategory", "animal", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.HiddenFor(m => Model.ID, Model.ID);
    <h4>Category Name:</h4>
    @Html.EditorFor(m => Model.Name, Model.Name);<br />
   <h4>Description:</h4>
    @Html.EditorFor(m => Model.Description, Model.Description);<br />
    if (Categories!=null)
    { 
    <h4>Parent Category:</h4>
    @Html.DropDownListFor(m => Model.ParentName, Categories,Model.ParentName);
    }
if (Model.Subcategories!=null&&Model.Subcategories.Any())
{ 
    <div id="subcategory">
                    @Html.Partial("CategoryList")</div>
}
if (Model.Animals!=null&&Model.Animals.Any())
{ 
    <div id="list">
        @Html.Partial("AnimalList")
    </div>
}
@Html.ActionLink("New Animal", "New", "Animal", new { category = Model.Name }, htmlAttributes: null);<br />
@Html.ActionLink("New Category", "NewCategory", "Animal", new { category = Model.Name }, htmlAttributes: null);
         }

SailingSite/Views/Animal/View1.cshtml
@{
    ViewBag.Title = "View1";
    Layout = "~/Views/Shared/_LayoutDescriptive.cshtml";
}

<h2>View1</h2>