SailingSite/Controllers/CrewController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Security;
using System.Web.Mvc;

namespace SailingSite.Controllers
{
    using System.Collections;
    using System.Net;
    using System.Threading.Tasks;

    using SailingSite.App_GlobalResources;
    using SailingSite.Common;
    using SailingSite.ViewModels;

    using SailingSiteModels.New;

    using SessionVariables = Resources.SessionVariables;

    public class CrewController : BaseController
    {
        
        //
        // GET: /Crew/
        public ActionResult Index()
        {
            var data=GetAll();
            return View(data);
        }

        public ActionResult Edit(int id)
        {
            return RedirectToAction("New", new { id = id });
        }

        [HttpPost]
        public ActionResult AddTags(int id, string tags)
        {
            this.CrewService.AddCrewTags(id, tags);
            var result = this.CrewService.GetCrewTag(id).ToArray();
            ViewData["controller"] = "crew";
            ViewData["entityID"] = id;
            return PartialView("TagList", result);
        }

      [HttpPost]
        public ActionResult Login(string username, string password, string redirecturl=null)
        {
            SailingSiteModels.New.CrewFoundation entity = null;
            try
            {
                this.LoginController.Login(username, password);
                
            }
            catch (Exception ex)
            {
                ViewBag[SessionVariables.Error] = SharedStrings.IncorrectUsernamePassword;
            }
            return PartialView(entity);

        }

        public ActionResult VerifyUserName(string userName)
      {
            bool result=false;
            result=this.CrewService.CheckUsername(userName);
            if (result)
            {
                throw new HttpException("This user already exists");
            }
            return new EmptyResult();

      }

        public ActionResult AddComment(int entityid, SailingSiteModels.New.Comment comment)
        {
            if (CurrentUser != null)
            {
                if (comment.ID < 1)
                {
                    comment.Created = DateTime.Now;
                    comment.CreatedbyID = CurrentUser.ID;
                }
                else
                {
                    comment.Updated = DateTime.Now;
                    comment.UpdatebyID = CurrentUser.ID;
                }
                this.CrewService.AddComment(entityid, comment);
            }
            return null;
        }

        [HttpPost]
        public ActionResult Create(SailingSiteModels.New.Crew entity, string tagList, HttpPostedFileBase file)
        {
            if (this.CurrentUser != null || (this.CurrentUser != null && this.CurrentUser.SID < Crew.SIDEnum.Admin))
            {
                var model = new RedirectModel() { Description = "You must be an admin to complete this task." };

                return this.View("NoPermissionPage", model);
            }

            int result = 0;
            try
            {
                if (file != null)
                {
                    var photo = new SailingSiteModels.New.Photo() { Name = entity.UserName, FileName = file.FileName, EntityName = entity.FullName, Subdirectory = @Resources.SessionVariables.ImageFolderCrew };
                    photo.ID = this.PhotoService.SavePhoto(file, photo, this.Context, Server.MapPath("~/imagedir"));
                    entity.ProfilePhoto = photo;
                }
                
                if (entity.ID > 0)
                {
                    result = entity.ID;
                    this.CrewService.Update(entity, this.Context);
                }
                else
                {
                    result=this.CrewService.Create(entity, this.Context);
                }
                if (tagList != null)
                {
                    this.CrewService.AddCrewTags(result, tagList);
                }
            }
            catch (Exception e) { 
                throw new HttpException(500,e.Message);
            }
            if (result == 0)
            {
                throw new HttpException(500, "Entity could not be created.");
            }
            base.FlagCacheUpdate(StaticTokens.CachingTokens.CrewEnum);
            return RedirectToAction("Index");
        }

        public ActionResult Delete(int id)
        {
            if (this.CurrentUser != null || (this.CurrentUser != null && this.CurrentUser.SID < Crew.SIDEnum.Admin))
            {
                return new HttpStatusCodeResult(HttpStatusCode.Forbidden, "Authentication error.  You must log in to perform this action.");
            }
            if (CurrentUser != null)
            {
                this.CrewService.Delete(id, CurrentUser.ID, this.Context);
                var data = GetAll();
                base.FlagCacheUpdate(StaticTokens.CachingTokens.CrewEnum);
                return new HttpStatusCodeResult(HttpStatusCode.Accepted);
            }
            else
            {
                throw new HttpException(500, "Authentication error.  You must log in to perform this action.");
            }

        }

        public async Task<ActionResult> VerifyIdentity(string username)
        {
            this.GetSessionVariables();
            IEnumerable<SecurityQuestion> data = null;
            try
            {
                data = await this.CrewService.GetQuestions(username, this.Context);
            }
            catch
            {
                return new HttpStatusCodeResult(HttpStatusCode.Conflict, "User not found");
            }
            return this.PartialView("SecQuestions", data);
        }

        [HttpPost]
        public async Task<ActionResult> PostAnswers(IEnumerable<SecurityQuestion> data, int id)
        {
            //Next
            var token = await this.CrewService.MatchAnswersAndSetToken(id, data, this.Context);
            Dictionary<int, string> result = new Dictionary<int, string>();
            result.Add(id, token);
            return this.View(result);
        }

        public async Task<ActionResult> CheckPassword(string password)
        {
            if (Crew.VerifyPasswordRequirements(password))
            {
                return new HttpStatusCodeResult(HttpStatusCode.Accepted);
            }
            else
            {
                return new HttpStatusCodeResult(
                    HttpStatusCode.ExpectationFailed,
                    "Password does not meet requirements.  Please verify your password is between 7 and 28 characters and has an uppercase, lowercase and number.");
            }
        }

        [HttpPost]
        public async Task<ActionResult> ProcessAnswer(SecurityQuestion securityQuestion)
        {
            var crew = Session[StaticTokens.CachingTokens.UserSessionResources] as CrewSecurity;
            if (securityQuestion == null || !this.ModelState.IsValid)
            {
                return new HttpStatusCodeResult(
                    HttpStatusCode.BadRequest,
                    "Both question and answer must be 7-255 characters in length.");
            }
            
            if (crew == null || crew.ID != securityQuestion.CrewID)
            {
                return new HttpStatusCodeResult(
                    HttpStatusCode.Forbidden,
                    "It appears you are not logged in under the correct credentials.  Please log back in and try again.");
            }
            if (this.ModelState.IsValid && securityQuestion != null)
            {
                try
                {
                    await this.CrewService.ProcessQuestion(securityQuestion);
                    
                }
                catch (Exception ex)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.Conflict, ex.Message);
                }
            }
            return new HttpStatusCodeResult(HttpStatusCode.Accepted);
        }

        public async Task<ActionResult> NewQuestion()
        {
            var crew = Session[StaticTokens.CachingTokens.UserSessionResources] as CrewSecurity;
            if (crew == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest, "Sorry.  You must be logged in to do that.");
            }
            var question = new SecurityQuestion() { CrewID = crew.ID };
            return this.PartialView("_QuestionPartial", question);
        }

        public async Task<ActionResult> UpdatePassword(string token, string password, int id)
        {
            await this.CrewService.ResetPassword(id, token, password, this.Context);
            return new HttpStatusCodeResult(HttpStatusCode.Accepted);
        }

        public async Task<ActionResult> LoadQuestions()
        {
            IEnumerable<SecurityQuestion> result= null;
            if (this.CurrentUser != null)
            {
                result = await this.CrewService.GetQuestions(this.CurrentUser.ID, this.Context);
            }
            return this.View(result);
        }

        public ActionResult New(int? id=null)
        {
            this.GetSessionVariables();
            SailingSiteModels.New.Crew result = new SailingSiteModels.New.Crew();
            result.Password = "null";
            if (id != null)
            {
                var entity = this.CrewService.Get(new GeneralSearchRequest
                {
                    ID = id
                });
                result = entity.FirstOrDefault();
            }
            return View(result);
        }

        public ActionResult Get(int id)
        {
            this.GetSessionVariables();
            SailingSiteModels.New.Crew data = this.CrewService.GetSingle(id);
            if (data != null)
            {
                return View(data);
            }
            else return this.View("NullObject");
        }

SailingSite/Views/Fleet/Get.cshtml
@using System.Linq
@using SailingSite.App_GlobalResources
@model SailingSiteModels.New.Fleet
@{
    var foundedDate = Model.FoundedDate == null ? SharedStrings.UnknownData : Model.FoundedDate.Value.ToShortDateString();
    var captain = Model.Captain == null ? SharedStrings.UnknownData : Model.Captain.FullName();
    bool? isEditor = ViewData["editable"] as bool?;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title></title>
</head>
<body>
    <div>
        @if (Model!=null)
        {
            <div class="well-lg">
                <div class="col-sm-6"></div>
                <h3>@Model.Name</h3>
                <i>@SharedStrings.FleetDateFoundedLabel @foundedDate</i> <br/>
                <i>@SharedStrings.FleetCaptain @captain</i>

            </div>
            <div class="col-sm-6"><b>@SharedStrings.SailCountLabel</b> @Model.SailTotal<br/><b>@SharedStrings.MileCount</b>@Model.MileTotal
            </div>
            <div class="col-sm-6">@SharedStrings.FleetCrewCount @Model.CrewTotal</div>
            
            if (Model.VesselEntries != null && Model.VesselEntries.Any())
            { 
                <h3>Vessels: @Model.VesselEntries.Count</h3>
                <table id="vesselTable" name="vesselTable">
                    <thead class="Label">
                        <th>Name</th>
                    <th>Length</th>
                    <th>Total Sails</th>
                    <th>Total Miles</th>
                    @if (isEditor==true)
                    {
                        <th>Remove</th>
                    }
                    </thead>
                    <tbody>
                        @foreach (var vessel in Model.VesselEntries.OrderBy(i => i.MilesSailed).ThenBy(i => i.SailTotal))
                        {
                            var guid = Guid.NewGuid().ToString();
                            if (vessel != null && vessel.Vessel != null)
                            {
                                var name = vessel.NickName == null ? vessel.Vessel.Name : string.Format("\"{0}\"", vessel.NickName);
                                <tr class="data" id="@guid">
                                    <td>@Html.ActionLink(name, Resources.ActionVerbs.Get, "Vessel", new { id = vessel.Vessel.ID })</td>
                                    <td>@vessel.Vessel.Length</td>
                                    <td>@vessel.SailTotal</td>
                                    <td>@vessel.MilesSailed</td>
                                    <td><span class="ui-icon ui-icon-closethick" onclick="removeVesselFromFleet(@vessel.Vessel.ID,@Model.ID,@guid)"></span></td>
                                </tr>
                            }
                        }
                    </tbody>
                </table>
            }
            
            if (Model.Crew != null && Model.Crew.Any())
            { 
                <h3>Crew: @Model.Crew.Count</h3>
                <table id="crewTable" name="crewTable">
                    <thead>
                        <th>Name</th><th>Sail Count</th><th>Mile Count</th><th>Hour Count</th>
                    </thead>
                    <tbody>
                        @foreach (var crew in Model.Crew.OrderBy(i=>i.LastName))
                        {
                            
                            var fullName=crew.FirstName+" "+crew.LastName;
                            <tr>
                                <td>
                                    @Html.ActionLink(fullName, Resources.ActionVerbs.Get, "Crew", new { id = crew.ID })
                                </td>
                                <td>
                                    @crew.SailCount
                                </td>
                                <td>
                                    @crew.MileCount
                                </td>
                                <td>
                                    @crew.HourCount
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            }
        }
    </div>
</body>
</html>
<script type="text/javascript">
    function removeVesselFromFleet(vesselId, fleetId, guid) {

        $.ajax({
            url: "/Fleet/RemoveFromFleet/",
            data: { "id": vesselId, "fleetId": fleetId },
            type: "PUT",
            dataType: "html",
            failure: "generalFailure",
            success: function () {
                var tdselect = "#" + guid;
                var tr = $(tdselect);
                var parent = tr.parentNode;
                parent.removeChild(tr);
            }
        });
    }
</script>

SailingSite/Views/Fleet/Index.cshtml
@using SailingSite.App_GlobalResources
@model IEnumerable<SailingSiteModels.New.FleetBase>
@{
    
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width"/>
    <title></title>
</head>
<body>
<div>
    <table id="fleetTable">
        <thead>
        <tr>
            <th>
                @SharedStrings.Name
            </th>
            <th>@SharedStrings.CrewCount</th>
            <th>@SharedStrings.VesselCount</th>
            <th>@SharedStrings.MileCount</th>
            <th>@SharedStrings.EditEntity</th>
            <th>@SharedStrings.DeleteEntity</th>
            <th></th>
        </tr>
        </thead>
        @if (Model != null && Model.Any())
        {
            foreach (var fleet in Model)
            {
                var crewCount = fleet.CrewCount == null ? 0 : (int)fleet.CrewCount;
                var vesselCount = fleet.VesselCount == null ? 0 : (int)fleet.VesselCount;
                decimal mileCount = fleet.MileCount == null ? 0 : (decimal)fleet.MileCount;
                <tr>
                    <td>@Html.ActionLink(fleet.Name, Resources.ActionVerbs.Get, new { id = fleet.ID })</td>
                    <td>@crewCount</td>
                    <td>@vesselCount</td>
                    <td>@mileCount</td>
                    <td><a href="Edit/@fleet.ID" class=" editlink"><span style="float: left" class="ui-icon ui-icon-pencil"></span></a></td>
                    <td><a href="" data-id="@fleet.ID" class="deleteLink"><span style="float: left" class="ui-icon ui-icon-trash"></span></a></td>

                </tr>
            }
        }
        else
        {
            <tr>
                <td>No records found.</td>
            </tr>
        }

    </table>
</div>
</body>
</html>
<script type="text/javascript">
    $(document).ready(function () {



        $(".deleteLink").off("click").on("click", function () {
            var id = $(this).attr("data-id");
            $.ajax({
                type: "GET",
                url: "@Url.Action("Delete", "Vessel")",
                data: { "id": id },
                success: function (data, response, request) {
                    toastr.success("Deletion Successful.", "@SharedStrings.SuccessLabel");
                },

                error: function (data, response, request) {
                    toastr.error(data, "@SharedStrings.ErrorLabel");
                    return false;
                }
            });
        }
                );
    }
                );</script>

SailingSite/Views/Fleet/New.cshtml
@using SailingSite.App_GlobalResources
@model SailingSiteModels.New.Fleet
@{
    if (Model!=null&&Model.ID > 0)
    {
        ViewData["entityID"] = Model.ID;
    }
    else {
        ViewData["entityID"] = 0;
    }
    
    ViewData["controller"]="Vessel";
    IEnumerable<SailingSiteModels.New.Tags> tags = null;
    IEnumerable<SailingSiteModels.New.FleetBase> fleets = null;
    IEnumerable<SailingSiteModels.New.CrewFoundation> crew = null;
    bool update = Model!=null&&Model.ID != 0;
    var foundedDate = Model.FoundedDate == null ? DateTime.Now.ToShortDateString() : Model.FoundedDate.Value.ToShortDateString();
    var name = Model.Name == null ? String.Empty : Model.Name;
    var updateString = update ? "Update" : "Add";
    if (Session["Crew"] != null)
    {
        crew = Session["Crew"] as IEnumerable<SailingSiteModels.New.CrewFoundation>;
    }
    if (Session["Fleets"] != null)
    {
        fleets = Session["Fleets"] as IEnumerable<SailingSiteModels.New.FleetBase>;
    }
    if (Session["Tags"] != null)
    {
        tags = Session["Tags"] as IEnumerable<SailingSiteModels.New.Tags>;
    }
}
@*<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
<link href="~/bundles/jquery-ui.min.css" rel="stylesheet" />
<script src="~/Scripts/toastr.js"></script>
<script src="/scripts/jquery.validate.min.js" type="text/javascript"></script>
<script src="/scripts/jquery.validate.unobtrusive.min.js" type="text/javascript"></script>
<link href="~/Content/toastr.css" rel="stylesheet" />*@

<div class="container">
    <div class="col-lg-5">
        @using (Html.BeginForm("create", "fleet", FormMethod.Post, new { enctype = "multipart/form-data", id = "createForm" }))
        {
            <input type="hidden" id="fleetID" name="ID" value=@Model.ID>
            <h3>@SharedStrings.FleetName</h3>
            <input type="text" name="Name" id="Name" value="@name"/><br/>
            <h3>@SharedStrings.FleetCaptain</h3>
            <select id="crewTable" name="Captain.ID">
                @foreach (var member in crew.OrderBy(i => i.LastName))
                {
                    var selected = Model != null && Model.Captain != null && Model.Captain.ID == member.ID ? " selected=\"selected\"" : string.Empty;
                    <option value="@member.ID" @selected>@member.FirstName @member.LastName</option>
                }
            </select><br/>

            <h3>@SharedStrings.FleetDateFoundedLabel</h3>
            <input type="text" name="FoundedDate" class="datepicker" value="@foundedDate"/>
            <br/>

            <h3>@SharedStrings.DescriptionGeneral</h3>
            @Html.TextAreaFor(m => m.Description)<br/>


            @Html.Partial("TagList", Model.Tags)
            <input type="button" class="submitbutt" value=@updateString/>
            <br/>
        }
    </div>
    @if (Model.ID>0)
    {
        <div class="col-lg-7">
            <h3>Vessel Assignment</h3>
        <div>
            <div id="fleetContainer">
                @if (Model.VesselEntries != null && Model.VesselEntries.Any(i=>i!=null))
                {
                    @Html.Partial("_VesselEntryList",Model.VesselEntries)
                }
            </div>

            <input type="button" id="fleetAdder" data-id="@Model.ID" value="Add a Vessel"/>
        </div>
        </div>
    }
</div>





<script type="text/javascript">
    var name = "@Model.Name";
    var form = $("#createForm");
    $(document).ready(function() {
        $("#fleetAdder").off("click").on("click", addVesselEntry);
        $(".datepicker").datepicker();
        $(".submitbutt").off("click").on("click", function() {
            form.validate();
            var valid = form.valid();
            if (valid == true) {

                submit();
            }
        });;
        $.validator.unobtrusive.parse(form);

    });

    function addVesselEntry() {
        var fleetID = $(this).attr('data-id');
        var urlPointer = '/Fleet/AddVesselEntry';
        $.ajax({
            url: urlPointer,
            data: { "fleetID": fleetID },
            error: function (data) {
                toastr.error('Avast!', data);
            },
            success: function (data) {
                $('#fleetContainer').append(data);
            }

        });
    }

    function submit() {
        var val = $("#Name").val();
        if (val != name) {
            $.ajax({
                type: "GET",
                url: "@Url.Action("VerifyName", "Fleet")",
                data: { "name": val },
                success: function(data, response, request) {
                    var form = $("#createForm");
                    form.submit();
                },

                error: function() {
                    toastr.error("@SharedStrings.FleetNameTakenError", "@SharedStrings.ErrorLabel");
                    return false;
                }
            });
        } else {

            form.submit();
        }
    }

    function deleteVesselEntry() {
        var vesselID = $(this).attr('data-vesselid');
        var fleetID = $(this).attr('data-fleetid');
        if (fleetID != undefined && vesselID != undefined) {
            var urlPointer = '/Fleet/RemoveVesselFromFleet';
            $.ajax({
                url: urlPointer,
                data: { "vesselID": vesselID, "fleetID": fleetID },
                error: function (data) {
                    toastr.error('Avast!', data);
                },
                success: function (data) {
                    toastr.success('Entry deleted!', 'Ahoy!');
                }

            });
        }
    }

    function submitVesselEntry() {
        var form = $(this).closest('form');
        var formData = new FormData(form[0]);
        var urlPointer = '/Fleet/AddVesselToFleet';
        $.ajax({
            url: urlPointer,
            data:  formData,
            type: "POST",
            processData: false,
            contentType: false,
            error: function (data) {
                toastr.error('Avast!',data);
            },
            success: function (data) {
                $('#fleetContainer').html(data);
            }

        });
    }
    

</script>

SailingSite/Views/Fleet/_VesselEntry.cshtml
@model SailingSiteModels.New.VesselEntry
@{
    string dateIdentifier = String.Format("{0}datepicker", Guid.NewGuid().ToString());
}

<form class="vesselEntry">
    @Html.HiddenFor(i => i.ID)

    
    @Html.HiddenFor(i => i.FleetID)
    <div class="col-sm-5">
        <b>Vessel:</b>@Html.Partial("_VesselDD")
    </div>
    <div class="col-sm-4">
        <b>Date Added:</b>@Html.TextBoxFor(i => i.DateAdded, new { id = dateIdentifier })<br />
    </div>
    <div class="col-sm-3">
        <b>Rank</b>@Html.TextBoxFor(i => i.Ordinal)
        <input type="button" class="vesselEntryAdd" value="Add/Update" />
        @if (Model.ID > 0 && Model.Vessel != null)
        {
            <a href="#" data-fleetid="@Model.ID" data-vesselid="@Model.Vessel.ID" class="vesselEntryDeleter"><i class="fa fa-trash-o fa-2"></i></a>
        }
    </div>
</form>

<script type="text/javascript">
    $(document).ready(function () {
        $('#@dateIdentifier').datepicker();
        $('.vesselEntryAdd').off('click').on('click', submitVesselEntry);
        $('.vesselEntryDeleter').off('click').on('click', deleteVesselEntry);
    });
</script>

SailingSite/Views/Fleet/_VesselEntryList.cshtml
@model IEnumerable<SailingSiteModels.New.VesselEntry>

@foreach (var entry in Model)
                    {
@Html.Partial("_VesselEntry", entry)
                    }