SailingSite/Controllers/VesselController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SailingSite.Controllers
{
    using System.ComponentModel.Design;
    using System.Net;

    using SailingSite.Common;
    using SailingSite.ViewModels;

    using SailingSiteModels.New;
    using SailingSiteModels.New.Debug;

    public class VesselController : BaseController
    {
        //
        // GET: /Vessel/
        public ActionResult Index(int? fleetId=null)
        {
            this.GetSessionVariables();
            ViewData[Resources.SessionVariables.FleetNameViewBagVariable] = fleetId;
            var data = Sailservice.GetVesselBases(fleetId);
            
            return View(data);
        }

        [HttpGet]
        public ActionResult Get(int id)
        {
            var data=Sailservice.GetVessel(id);
            if (data != null)
            {
                return View(data);
            }
            else return this.View("NullObject");
        }

        public ActionResult GetSheetSail(int id)
        {
            var data = Sailservice.GetSheetSail(id);
            return this.PartialView("EditSheetSail", data);
        }

        public ActionResult Delete(int id, int? fleetId = null)
        {

            if (this.CurrentUser == null
                || (this.CurrentUser != null
                    && !this.Sailservice.isUserVesselCrewOrSecurity(id, this.CurrentUser.ID, true)))
            {
                return new HttpStatusCodeResult(HttpStatusCode.Forbidden, "You must be logged in as a verified member to perform that action.");
            }

            var data = Sailservice.GetVesselBases(fleetId);
            this.FlagCacheUpdate(StaticTokens.CachingTokens.VesselEnum);
            return View("_VesselUL", data);
        }

        [HttpGet]
        public ActionResult New(int? id)
        {

            if (this.CurrentUser == null || this.CurrentUser.SID < Crew.SIDEnum.PowerUser)
            {
                this.LoggingService.GenerateLog("Fail-User attempted to create a vessel with no permissions.", Log.LogTypes.AuditAdmin, this.Context);
                var redirectModel = new RedirectModel() { ActionName = "Index", ControllerName = "Admin", UserBlocked = true, Description = "You do not have permission to access this page." };
                return this.View("NoPermissionPage");
            }
            this.GetSessionVariables();
            Vessel data = null;
            if (id == null || id < 1)
            {
                data = this.Sailservice.JiffyVessel(this.Context);
            }
            else
            {
                data=this.Sailservice.GetVessel((int)id);
            }

            
            
            return View(data);
        }

        /// <summary>
        /// The add sheet sail.
        /// </summary>
        /// <param name="entity">
        /// The entity.
        /// </param>
        /// <returns>
        /// The <see cref="ActionResult"/>.
        /// </returns>
        [HttpPost]
        public ActionResult AddSheetSail(SheetSail entity)
        {
            // adds the sheetsail then 
             this.Sailservice.AddSheetSailToExistingVessel(entity, this.Context);
            var result = this.Sailservice.GetVessel(entity.Vessel.ID);
            return this.PartialView("ExistingSheetSail", result);
        }

        /// <summary>
        /// The update sheet sail.
        /// </summary>
        /// <param name="entity">
        /// The entity.
        /// </param>
        /// <returns>
        /// The <see cref="ActionResult"/>.
        /// </returns>
        [HttpPatch]
        public ActionResult UpdateSheetSail(SheetSail entity)
        {
            this.Sailservice.UpdateSheetSail(entity, this.Context);
            return new HttpStatusCodeResult(HttpStatusCode.OK);
        }

        [HttpDelete]
        public ActionResult DeleteSheetSail(int id)
        {
            this.Sailservice.DeleteSheetSail(id, this.Context);
            return new HttpStatusCodeResult(HttpStatusCode.OK);
        }

        public ActionResult SearchByLetter(string letter)
        {
            var request = new GeneralSearchRequest();
            if (string.IsNullOrEmpty(letter) || !char.IsLetter(letter[0]))
            {
                this.Sailservice.SearchVessel(request);
            }
            request.FirstInitial = letter;
            var data = this.Sailservice.SearchVessel(request);
            return this.View("_VesselSearch", data);

        }

        /// <summary>
        /// The edit sheet sail.
        /// </summary>
        /// <param name="id">
        /// The id.
        /// </param>
        /// <returns>
        /// The <see cref="ActionResult"/>.
        /// </returns>
        [HttpGet]
        public ActionResult EditSheetSail(int id)
        {
            var result = this.Sailservice.GetSheetSail(id);
            return this.View(result);
        }

        /// <summary>
        /// The create new sheet sail.
        /// </summary>
        /// <param name="parentId">
        /// The parent id.
        /// </param>
        /// <returns>
        /// The <see cref="ActionResult"/>.
        /// </returns>
        [HttpGet]
        public ActionResult CreateNewSheetSail(int parentId)
        {
            var result = new SheetSail() { Vessel = new Vessel() { ID = parentId } };
            return this.PartialView("EditSheetSail", result);
        }

        [HttpPost]
        public ActionResult AddTags(int id, string tags)
        {
            Sailservice.AddVesselTags(id,tags);
            var result = Sailservice.GetVesselTag(id).ToArray();
            this.ViewData["controller"] = "vessel";
            this.ViewData["entityID"] = id;
            base.FlagCacheUpdate(StaticTokens.CachingTokens.TagEnum);
            return this.PartialView("TagList", result);
        }

        [HttpPost]
        public ActionResult DeleteTag(int id, int entityId)
        {
            Sailservice.DeleteVesselTag(id, entityId);
            var result = Sailservice.GetVesselTag(id).ToArray();
            ViewData["controller"] = "animal";
            ViewData["entityID"] = id;
            return PartialView("TagList", result);
        }

        public void AddPhoto(int entityid, int photodId)
        {
            Sailservice.AddVesselPhoto(photodId, entityid);
        }

        public void DeletePhoto(int photoId, int entityId)
        {
            Sailservice.DeleteVesselPhoto(photoId, entityId);
        }

        /// <summary>
        /// The create.
        /// </summary>
        /// <param name="entity">
        /// The entity.
        /// </param>
        /// <param name="tagList">
        /// The tag list.
        /// </param>
        /// <param name="file">
        /// The file.
        /// </param>
        [HttpPost]
        public ActionResult Create(SailingSiteModels.New.Vessel entity, string tagList, HttpPostedFileBase file = null)
        {
            if (this.CurrentUser == null
                || (this.CurrentUser != null
                    && this.Sailservice.GetCrewSID(this.CurrentUser.ID) < Crew.SIDEnum.StandardUser))
            {
                return new HttpStatusCodeResult(HttpStatusCode.Forbidden, "You must be logged in as a verified member to perform that action.");
            }

            if (file != null&&entity!=null)
            {
                var photo = new SailingSiteModels.New.Photo() { Name = entity.Name, FileName = file.FileName, EntityName = entity.Name, Subdirectory = Resources.SessionVariables.ImageFolderVessel };
                photo.ID = this.PhotoService.SavePhoto(file, photo, this.Context, Server.MapPath("~/imagedir"));
                entity.Photo = photo;
            }
            if (entity.ID > 0)
            {
                if (this.Sailservice.isUserVesselCrewOrSecurity(entity.ID,this.CurrentUser.ID, true))
                Sailservice.UpdateVessel(entity);
            }
            else
            {
                entity.ID = Sailservice.CreateVessel(entity, this.Context);
            }

            base.FlagCacheUpdate(StaticTokens.CachingTokens.VesselEnum);

            Sailservice.AddVesselTags(entity.ID, tagList);
            this.FlagCacheUpdate(StaticTokens.CachingTokens.VesselEnum);
            return this.RedirectToAction("Index");
        }

	}
}

SailingSite/Views/Vessel/EditSheetSail.cshtml
@using System.Collections
@using SailingSite.App_GlobalResources
@using SailingSite.Common
@using SailingSiteModels.New
@model SailingSiteModels.New.SheetSail
@{
    var options = new AjaxOptions
    {
        HttpMethod = "post",
        InsertionMode = InsertionMode.ReplaceWith,
        UpdateTargetId = "sailLockerUpdateDiv",
        OnFailure = "generalFailure(error)",
        OnSuccess = "generalSuccess('Sheet added')"
    };
    
    IEnumerable<Configuration> sailTypes = null;
    if (this.Session[StaticTokens.CachingTokens.SailConfigurationEnum] != null && this.Session[StaticTokens.CachingTokens.SailConfigurationEnum] is IEnumerable<Configuration>)
    {
        sailTypes = (IEnumerable<Configuration>)this.Session[StaticTokens.CachingTokens.SailConfigurationEnum];
    }
    var btnText = Model.ID > 0 ? "Submit Changes" : "Add";
}
<div class="container">
    @using (Ajax.BeginForm("AddSheetSail", "Vessel", null, options, new { id = "createSailSheetForm" }))
    {
        <input type="hidden" name="ID" value="@Model.ID"/>
        <input type="hidden" name="Vessel.ID" value="@Model.Vessel.ID"/>
        <b>@SharedStrings.SheetSailTypeLabel</b>
        if (sailTypes != null && sailTypes.Any())
        {
            <select name="SailType.ID">
                @foreach (var type in sailTypes)
                {
                    var selected = Model.SailType != null && Model.SailType.ID == type.ID ? "selected" : string.Empty;
                    <option value="@type.ID" @selected>@type.Name</option>
                }
            </select><br/>
        }
        else
        {
            <i>There was an error loading the values.</i><br/>
        }
        <b>@SharedStrings.SheetSailLocationLabel</b>
        @Html.TextBoxFor(i => i.Location)<br/>
        <b>@SharedStrings.SheetSailArea</b>
        @Html.TextBoxFor(i => i.SailArea)<br/>
        <b>@SharedStrings.SheetSailLettering</b>
        @Html.TextBoxFor(i=>i.SailLettering)<br/>
        <input id="addNewSheetSail" type="button" value="@btnText"/>
    }
</div>
<script type="text/javascript">
    $(document).ready(function() {
        $('#addNewSheetSail').off('click').on('click', submitSailSheet);
    });

    function submitSailSheet() {

        $.ajax({
            type: "POST",
            url: "@Url.Action("AddSheetSail", "Vessel")",
            data: $('#createSailSheetForm').serialize(),
            error: function(request, data, response) {
                generalFailure(response);
            },
            success: function(data) {
                generalSuccess('Sheet added');
                $('#sailLockerUpdateDiv').html(data);
                loadNewComment();
            }


        });
    }

    function loadNewComment() {
        $.ajax({
            type: "Get",
            url: "@Url.Action("CreateNewSheetSail", "Vessel")",
            data: { parentId: @Model.Vessel.ID },
            error: function(request, data, response) {
                generalFailure(response);
            },
            success: function(data) {
                generalSuccess('Sheet added');
                $('#sailLockerNewDiv').html(data);
            }
        });
    }
</script>

SailingSite/Views/Vessel/ExistingSheetSail.cshtml
@using SailingSite.App_GlobalResources
@model SailingSiteModels.New.Vessel
@if (Model.SailLocker != null && Model.SailLocker.Any())
{
    //Todo: chnge model to IEnum of sheetsails.
    <b>@SharedStrings.SailLockerLabel</b>
    <table>
        <tr>
            <th>Sail Type</th>
            <th>Location</th>
            <th>Rolling Furler?</th>
            <th>Edit</th>
            <th>Delete</th>
        </tr>
        @foreach (var sail in Model.SailLocker)
        {
            var rollingFurler = sail.RollingFurling == true ? "Yes" : "No";
            var uid = new Guid().ToString();

            <tr id="@uid">
                <td>
                    @sail.SailType.Description
                </td>
                <td>
                    @sail.Location
                </td>
                <td>
                    @rollingFurler
                </td>
                <td>
                    <a class="editSheetSailRow" data-id="@sail.ID" href="#"><span class="ui-icon-wrench"></span> </a>
                </td>
                <td>
                    <a class="deleteSheetSailRow" data-id="@sail.ID" href="#"><span class="ui-icon ui-icon-trash"></span> </a>
                </td>
            </tr>
        }
    </table>
}
<script type="text/javascript">
    $(document).ready(function() {
        $('.editSheetSailRow').off('click').on('click', updateSheetSail);
        $('.deleteSheetSailRow').off('click').on('click', deleteSheetSail);
    });

    function deleteSheetSail() {
        var id = $(this).attr('data-id');
        $.ajax({
            type: "Get",
            url: "@Url.Action("DeleteSheetSail", "Vessel")",
            data: { id: id },
        error: function(request, data, response) {
            generalFailure(response);
        },
        success: function(data) {
            $('#sailLockerUpdateDiv').html(data);
        }
    });
    }

    function updateSheetSail() {
        var id = $(this).attr('data-id');
        $.ajax({
            type: "Get",
            url: "@Url.Action("GetSheetSail", "Vessel")",
            data: { id: id },
        error: function(request, data, response) {
            generalFailure(response);
        },
        success: function(data) {
            $('#sailLockerNewDiv').html(data);
        }
    });
    }
</script>

SailingSite/Views/Vessel/Get.cshtml
@using System.Threading
@using SailingSite.App_GlobalResources
@using SailingSite.Common
@{
    @model SailingSiteModels.New.Vessel
    }

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title></title>
</head>
<body>
    <div class="title">
    @if (Model.Photo != null && Model.Photo.ThumbPath != null)
    { 
        <img class="thumbnail" src="@Model.Photo.ThumbPath" />
    }
    
        <h3>@Model.Name</h3></div>
    <div>
        <table>
            <tr>
                <td>@SharedStrings.VesselSpecsLabel</td>
            </tr>
            <tr>

                <td><label><span class="fieldLabel">@SharedStrings.VesselModel</span>@Model.Model.GetWebProp()</label></td><td><label><span class="fieldLabel">@SharedStrings.VesselRig</span>@Model.Rig.GetWebProp()</label></td>
                </tr>
            <tr>
                <td><label><span class="fieldLabel">@SharedStrings.VesselLength</span>@Model.Length.GetWebProp()</label></td>
                <td><label><span class="fieldLabel">@SharedStrings.VesselBeam</span>@Model.Beam.GetWebProp()</label></td>
            </tr>
            @if (Model.NumberOfMasts+Model.HoursCount+Model.MileTotal>0)
            {   
            <tr>
                <td><span class="fieldLabel">@SharedStrings.SailCountLabel</span>@Model.NumberOfMasts.GetWebProp()</td>
                <td><span class="fieldLabel">@SharedStrings.MileCountLabel</span>@Model.MileTotal.GetWebProp()</td>
                <td><span class="fieldLabel">@SharedStrings.HourCountLabel</span>@Model.HoursCount.GetWebProp()</td>
            </tr>
            }
        </table>
      @if (Model != null && Model.Sails != null && Model.Sails.Any())
      {
          var count = 0;
          @Html.Partial("Graphs/ISailableChart",Model)
          //var collection = Model.GenerateChartCollection();
          
          @*<div class="col-lg-12 chartContainer">
              @foreach (var chart in collection.Collection)
              {
                  if (chart != null)
                  {
                      var selected = count == 0 ? "selected" : string.Empty;
                      var divId = string.Format("chartId_{0}", chart.UID);

                      <div class="chartDiv @selected" id=@divId>
                          table:@(chart.Chart)
                      </div>
                      count++;
                  }
              }
          </div>
          <div class="col-lg-12"><select id="chartSelector">
              @foreach (var chart in collection.Collection)
              {
                  var targetId = string.Format("chartId_{0}", chart.UID);
                  <option data-target="@targetId">@chart.Descriptor</option>
              }
          </select></div>*@
      }
          @*var chart = collection.Collection.FirstOrDefault();
          if (chart != null)
          {
            <b>table:@(chart.Chart)</b>
          }
          if (Model.Sails.Count() > 1)
          {
              var chart2 = collection.Collection.ElementAt(1);
              <b>table:@(chart2.Chart)</b>
          }*@
      }
    </div>
    
    <div>
    <div id="accordion">
        <h3>@SharedStrings.IdentificationLabel</h3>
        <div>
            <table>
                <tr>
                    <td>
                        <span class="fieldLabel">@SharedStrings.VesselHullNumbers</span>@Model.HullNumbers.GetWebProp()
                    </td>
                    <td>
                        <span class="fieldLabel">@SharedStrings.VesselSailNumbers</span>@Model.SailNumbers.GetWebProp()
                    </td>
                </tr>
                <tr>
                    <td><span class="fieldLabel">@SharedStrings.VesselDistinguishingFeatures</span> @Model.DistinguishingFeatures</td>
                </tr>
            </table>
            
        </div>

        @if (Model.HullColors != null || Model.LetteringColors != null || Model.SailColors != null)

        {
            <h3>@SharedStrings.ColorsLabel</h3>
            <div>
                <table>
                    <tr>
                        <td><span class="fieldLabel">@SharedStrings.VesselHullColors</span>@Model.HullColors.GetWebProp()</td>
                        <td><span class="fieldLabel">@SharedStrings.VesselSailColors</span>@Model.SailColors.GetWebProp()</td>
                    </tr>
                    <tr>
                        <td><span class="fieldLabel">@SharedStrings.VesselNumberColors</span>@Model.LetteringColors.GetWebProp()</td>
                    </tr>
                </table>
            </div>
        }
}


        @if (Model.Crew != null && Model.Crew.Any())
        {
            <h3>@SharedStrings.CrewLabel@Model.Crew.Count()</h3>
            <div>
                @Html.Partial("CrewList", Model.Crew.OrderBy(i=>i.LastName))
            </div>
        }
        @if (Model.Sails != null && Model.Sails.Any())
        {
            <h3>Last @Model.Sails.Count() Sails</h3>
            <div>
                @Html.Partial("SailBaseTable", Model.Sails.OrderByDescending(i=>i.Date))
            </div>
        }
        @if (Model.Photos != null && Model.Photos.Any())
        {
            <h3>@SharedStrings.PhotoLabel @Model.Photos.Count()</h3>
            <div>
                @Html.Partial("PhotoCarousel", Model.Photos)
            </div>
        }
        @if (Model.AnimalsSpotted != null && Model.AnimalsSpotted.Any())
        {
            <h3>@SharedStrings.AnimalsSpottedLabel @Model.AnimalsSpotted.Count()</h3>
            <div>
                @Html.Partial("AnimalBaseList", Model.AnimalsSpotted.OrderBy(i=>i.Name))
            </div>
        }
    </div>
        </div>
</body>
</html>
<script>
    $(document).ready(function () {
        $('#chartSelector').off('change').on('change', flipChart);
        //$('#highcharts-0').off('load').on('load', renderChartIds());

        //renderChartIds();
    });
    //function renderChartIds() {
    //    var tags= $('#highcharts-0').find('.highcharts-xaxis-labels text tspan:contains("#sid")');
    //    $.each(tags, function(index, el) {
    //        var value = el.innerHTML;
    //        var indexofStr = parseInt(value.indexOf("#sid"));

    //        if (indexofStr==NaN) {
    //            return;
    //        }
    //        indexofStr += 4;
    //        var id = value.substring(indexofStr, value.length);
    //        var htmlVal = '<a href="/Sail/Get/' + id + '">View</a>';
    //        el.innerHTML=htmlVal;
    //    });
    //}


    function getLegend(input) {
        renderChartIds(input.value);
    }

    function renderChartIds(input) {

        if (input.indexOf == undefined) {
            input = input.value;
        }
        var indexofStr = parseInt(input.indexOf("#"));

            if (indexofStr == NaN) {
                return;
            }
            indexofStr += 1;
            var id = input.substring(indexofStr, input.length);
            var date = input.replace('#'+id, '');
            var htmlVal = '<a href="/Sail/Get/' + id + '">'+date+'</a>';
        return htmlVal;
    }

    function renderCrewIds(input) {

        if (input.indexOf == undefined) {
            input = input.value;
        }
        var indexofStr = parseInt(input.indexOf("#"));

        if (indexofStr == NaN) {
            return;
        }
        indexofStr += 1;
        var id = input.substring(indexofStr, input.length);
        var name = input.replace('cid#' + id, '');
        var htmlVal = '<a href="/Crew/Get/' + id + '">' + name + '</a>';
        return htmlVal;
    }

    function flipChart() {
        var container = $('.chartContainer');
        var selected=$(this).find('option:selected');
        var chartDivs=container.find('div.chartDiv');
        chartDivs.removeClass('selected');
        var target = selected.attr('data-target');
        var selector = '#' + target;
        $(selector).addClass('selected');
    }

    $("#accordion").accordion({
        collapsible: true
    });

    function hsToolTip() {
        var v = ' <b>' + this.seriesName + '</b>' + this.x + ':' + this.y;
        return v;
    }

</script>

SailingSite/Views/Vessel/Index.cshtml
@using System.Collections
@using System.Web.UI.WebControls
@using SailingSite.App_GlobalResources
@model IEnumerable<SailingSiteModels.New.VesselBase>
@{
    IEnumerable<SailingSiteModels.New.FleetBase> fleets= null;
    if (Session["Fleets"] != null)
    {
        fleets = Session["Fleets"] as IEnumerable<SailingSiteModels.New.FleetBase>;
    }
    int? id = (int?)ViewData[Resources.SessionVariables.FleetNameViewBagVariable];
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title></title>
</head>
<body>
<div>
    <table>
        <tr>
            <td>
                <h3>Vessels</h3></td>
            <td>
                <b>@SharedStrings.FleetLabel</b><br/>
                <selection id="fleetSelector">
                    <option data-id="~/vessel/">All Fleets</option>
                    @foreach (var fleet in fleets)
                    {
                        var selected = id != null && id == fleet.ID ? "selected=\"selected\"" : string.Empty;
                        <option data-id="~/vessel/@fleet.ID" @selected>@fleet.Name</option>
                    }
                </selection>
            </td>
        </tr>
        
    </table>
    @if (Model != null && Model.Any())
    {

        <div id="VesselList">
            <table>
                <tr>
                    <th>@SharedStrings.VesselName</th>
                    <th>@SharedStrings.VesselMakeModel</th>
                    <th>@SharedStrings.VesselLength</th>
                    <th>@SharedStrings.VesselCaptain</th>
                    <th>@SharedStrings.SailCount</th>
                    <th>@SharedStrings.MileCount</th>
                    <th>@SharedStrings.CrewCount</th>
                </tr>

                @foreach (var vessel in Model)
                {
                    int sailCount = vessel.NumberOfMasts > 0 ? vessel.NumberOfMasts : 0;
                    decimal mileCount = vessel.MileTotal > 0 ? vessel.MileTotal : 0;
                    int crewCount = vessel.CrewTotal > 0 ? vessel.CrewTotal : 0;

                    <tr>
                        <td>@Html.ActionLink(vessel.Name, "Get")</td>
                        @* ADD EDIT/DELETE TO FIRST TD *@
                        <td>@vessel.Model</td>
                        <td>@vessel.Length</td>
                        <td>@vessel.Captain</td>
                        <td>@sailCount</td>
                        <td>@mileCount</td>
                        <td>@mileCount</td>
                        <td>@crewCount</td>
                    </tr>
                }
            </table>
        </div>
    }
</div>
</body>
</html>

SailingSite/Views/Vessel/_SailLocker.cshtml
@using SailingSite.App_GlobalResources
@using SailingSiteModels.New
@model SailingSiteModels.New.Vessel
<div id="sailLockerUpdateDiv">
    @Html.Partial("ExistingSheetSail", Model)
</div>