SailingSite/Controllers/CommentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SailingSite.Controllers
{
    using System.Net;

    using Microsoft.Ajax.Utilities;

    using SailingSite.App_GlobalResources;
    using SailingSite.Common;
    using SailingSite.Services;

    using SailingSiteModels.New;

    public class CommentController : BaseController
    {
        // GET: Comment
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult GetSailReport(int trackId)
        {
            var result = this.CommentService.GetSailReport(trackId);
            return this.PartialView("SailReport/SailReportPartial", result);
        }

        [HttpPost]
        public ActionResult Create(SailingSiteModels.New.Comment entity, string tags)
        {
            if (entity != null && !string.IsNullOrEmpty(entity.Message))
            {
                this.Session[Resources.SessionVariables.TemporaryComment] = entity;
                this.GetSessionVariables();

                if (this.CurrentUser == null)
                {
                    return new HttpStatusCodeResult(
                        HttpStatusCode.BadRequest,
                        "You must be logged in to create or edit a comment.");
                }

                if (entity.ID > 0)
                {
                    entity.Updated = DateTime.Now;
                    entity.ModifiedBy = this.CurrentUser;
                    this.CommentService.Update(entity);

                }
                else
                {
                    entity.Created = DateTime.Now;
                    entity.CreatedBy = this.CurrentUser;
                    entity.CreatedbyID = this.CurrentUser.ID;
                    try
                    {
                        entity.ID = this.CommentService.Create(entity);
                    }
                    catch (Exception ex)
                    {
                        return new HttpStatusCodeResult(HttpStatusCode.BadRequest, ex.Message);
                    }
                }

                if (tags != null)
                {
                    this.CommentService.AddTags(entity.ID, tags);
                }
                return new HttpStatusCodeResult(HttpStatusCode.OK);
            }
            
            return new HttpStatusCodeResult(HttpStatusCode.BadRequest , SharedStrings.EmptyOrNullCommentWarning);
           
        }

        public ActionResult Get(int id)
        {
            this.GetSessionVariables();
            var data = CommentService.Get(id);
            IsCreator(data);
            return View(data);
        }

        public ActionResult New(int? id = null)
        {
            this.GetSessionVariables();
            SailingSiteModels.New.Comment data=new SailingSiteModels.New.Comment();
            if (id != null&&id>0)
            {
                data = CommentService.Get((int)id);
            }
            return View(data);
        }

        [HttpPost]
        public ActionResult AddTags(int id, string tags)
        {
            CommentService.AddTags(id, tags);
            var result = CommentService.GetTags(id).ToArray();
            ViewData["controller"] = "comment";
            ViewData["entityID"] = id;
            return PartialView("TagList", result);
        }

        public ActionResult Delete(int id, string controller, int entityID)
        {
            if (CurrentUser != null)
            {
                CommentService.Delete(id, base.CurrentUser.ID);
                return RedirectToAction(Resources.ActionVerbs.GetCommentsPartial, controller, new { id = entityID });
            }
            else
            {
                throw new HttpException(500, "Authentication error.  You must log in to perform this action.");
            }
        }

        public ActionResult NewComment(DateTime? date, string message=null)
        {
            SailingSiteModels.New.Comment result=new Comment();
            if (date != null)
            {
                result.Created = (DateTime)date;
            }
            else
            {
                result.Created = DateTime.Now;
            }
            if (message != null)
            {
                result.Subject = message;
            }
            return this.PartialView("_Comment,", result);

        }

        [HttpPost]
        public ActionResult DeleteTag(int id, int entityId)
        {
            CommentService.DeleteTag(id, entityId);
            var result = CommentService.GetTags(id);
            ViewData["controller"] = "comment";
            ViewData["entityID"] = id;
            return PartialView("TagList", result);
        }
    }
}

SailingSite/Views/Comment/Get.cshtml
@using SailingSite.App_GlobalResources
@using SailingSiteModels.Common
@model SailingSiteModels.New.Comment
@{
    bool? isEditor = ViewData["editable"] as bool?;
    // TODO: Add this all to a partial and have it load in a modular.
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title></title>
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="well well-sm">
                @if (isEditor == true)
                {
                    <div class="float-right">
                        @Html.ActionLink(SharedStrings.EditEntity, Resources.ActionVerbs.New, "Comment", new { id = Model.ID }, null)

                        <span class="ui-icon ui-icon-wrench">
                        </span>

                    </div>
                }
                <h3>@Model.Subject</h3>
                @if (!string.IsNullOrEmpty(Model.Title))
{
                    <span class="fieldLabel">
                        @SharedStrings.CommentTitleLabel</span>
                    @Model.Title<br />
                    }
                    @if (Model.LogId != null && Model.Vessel != null)
{
                        <span class="fieldLabel"> @SharedStrings.CommentVesselLabel</span>
                        @Model.Vessel.Name<br />
}

                    @Html.Partial("_MetadataToggle",Model)
</div>
        </div>
            <div class="row">
                <div class="col-sm-6">
                                        @if (Model.WindSpeed != null)
                                        {
                                            <span class="@Model.WindColor">
                                                <span class="fieldLabel">@SharedStrings.SailLogWindReadingLabel</span> @Model.WindSpeed (@SharedStrings.BeaufortScaleLabel@((decimal)Model.WindSpeed).ToBeaufortScale() @if (Model.WindDirection != null)
                                                {
                                                    @(((int)Model.WindDirection).ToCompassBearing().ToString())
                                                }
                                            </span><br/>
                    }
                                        @if (Model.Barometer != null)
                    {
                        <span><span class="fieldLabel">@SharedStrings.SailLogBarometricPressure</span>@Model.Barometer<br/></span><br/>
                    }
                                        @if (Model.TempF != null)
                                        {
                                            <span> <span class="fieldLabel">@SharedStrings.SailLogTemperatureLabel</span>@Model.TempF</span><br/>
                    }
                    @if (Model.HelmsPerson != null)
                    {
                        <span><span class="fieldLabel">@SharedStrings.LogHelmsPersonLabel</span>@Model.HelmsPerson.FullName()</span><br/>
                    }
                                        @if (Model.MilesLogged != null)
                                        {
                                            <span><span class="fieldLabel">@SharedStrings.SailLogMilesLogged</span>@Model.MilesLogged</span><br/>
                    }
                </div>
                <div class="col-sm-6">
                    @if (Model.HeelPct != null)
                    {
                        <span class="fieldLabel">@SharedStrings.SailPercentHeelLabel</span> @Model.HeelPct<br/>
                    }
                    @if (Model.SeaState != null)
                    {
                        <span class="fieldLabel">@SharedStrings.SailLogSeaStateLabel</span>@Model.SeaState<br/>
                    }
                    @if (Model.CloudCover!=null)
                    {
                        <span class="fieldLabel">@SharedStrings.CloudCoverLabel</span> @Model.CloudCover<br/>
                    }
                    @if (Model.RainSeverity != null)
                    {
                        <span class="fieldLabel"> @SharedStrings.RainSeverityLabel</span> @Model.RainSeverity<br/>
                    }
                    @if (Model.Leeway != null)
                    {
                        <span class="fieldLabel">@SharedStrings.SailLeeway</span>
                        @Model.Leeway<br/>
                           
                    } 
                   @if (Model.CompassBearing != null)
                   {
                       <span><span class="fieldLabel">@SharedStrings.SailLogBearing</span> @Model.CompassBearing @(((int)Model.CompassBearing).ToCompassBearing().ToString())</span>
                   }
                    
                                        @if (Model.GPSCoords != null)
                                        {
                                            <span><span class="fieldLabel">@SharedStrings.SailLogGPSCoordinatesLabel@Model.GPSCoords</span><br /></span>
                    }

                </div>
            </div>
   
        <div class="row">
            <div class="col-sm-12">
                @if (Model.Message != null)
                {
                <span>@SharedStrings.CommentBodyLabel @Model.Message </span><br/>
                }
                <div id="accordion">
                    @if (Model.Animals != null && Model.Animals.Any())
                    {
                        <h3>@SharedStrings.AnimalsSpottedLabel</h3>
                        <div>
                            @Html.Partial("_ZooUL", Model.Animals)
                        </div>
                    }

                    @if (Model.Crew != null && Model.Crew.Any())
                    {
                        <h3>@SharedStrings.CrewLabel</h3>
                        <div>
                            @Html.Partial("_CrewUL", Model.Crew)
                        </div>
                    }

                    @if (Model.Vessels != null && Model.Vessels.Any())
                    {
                        <h3>@SharedStrings.VesselLabelPlural</h3>
                        <div>
                            @Html.Partial("_VesselUL", Model.Vessels)
                        </div>
                    }

                    @if (Model.Maneuvers != null && Model.Maneuvers.Any())
                    {
                        <h3>@SharedStrings.ManeuverLabelGeneric</h3>
                        <div>
                            @Html.Partial("_ManeuverUL", Model.Maneuvers)
                        </div>
                    }

                    @if (Model.Weather != null && Model.Weather.Any())
                    {
                        <h3>@SharedStrings.SailWeatherLabel</h3>
                        <div>
                            @Html.Partial("_WeatherUL", Model.Weather)
                        </div>
                    }

                    <h3>@SharedStrings.TagsCurrentLabel</h3>
                    <div>
                        @Html.Partial("TagListv3", Model)
                    </div>
                </div>

            </div>

        </div>
    </div>
</body>
</html>